Added Brokers and Broker manager
csweet22/CS2212Group44 pull request #5
Opened 2022-04-02 20:10 UTC by Shmoogus

2022-04-02 21:51 UTC, csweet22 requested changes

2022-04-02 21:51 UTC, csweet22 commented on src/main/java/cryptoTrader/utils/BrokerManager.java
> +    private static BrokerManager manager = null;
Could we name `manager` to `instance` just for consistency with the rest of the codebase?

2022-04-02 21:51 UTC, csweet22 commented on src/main/java/cryptoTrader/utils/BrokerManager.java
> +    }
Nitpicking (you can ignore or change this): Could we format this as `private BrokerManager() { }` if it's going to be empty?

2022-04-02 21:51 UTC, csweet22 commented on src/main/java/cryptoTrader/utils/BrokerManager.java
> +        }
This is more of a design question. So this says that if the broker already exists in the HashMap (With the name as the key), do not add another broker with the same name. Are we supposed to be able to add brokers with the same name but doing different strategies for different coins?

i.e. are we supposed to be able to handle a case where we have
`(name, coin, strategy)`
`broker1 BTC strat-A`
`broker1 ETH strat-B`

Let me know what you think 👍

2022-04-02 21:51 UTC, csweet22 commented on src/main/java/cryptoTrader/utils/BrokerManager.java
> +        Strategy strategy = StrategyFactory.getInstance().getStrategy(strategyName);
Beautiful factory.

2022-04-02 21:51 UTC, csweet22 commented on src/main/java/cryptoTrader/gui/MainUI.java
> +					}
>This is more of a design question. So this says that if the broker already exists in the HashMap (With the name as the key), do not add another broker with the same name. Are we supposed to be able to add brokers with the same name but doing different strategies for different coins?
>i.e. are we supposed to be able to handle a case where we have
>(name, coin, strategy)
>broker1 BTC strat-A
>broker1 ETH strat-B
>Let me know what you think 👍

Refer to above comment. You're probably more knowledgeable if we aren't supposed to allow duplicate brokers. 👍

2022-04-02 21:51 UTC, csweet22 commented on src/main/java/cryptoTrader/utils/BrokerManager.java
> +}
This might be something on my end, but on my version I'm seeing a `printBrokers()` method at the end of `BrokerManager.java`. Just letting you know that I think that the HashMap isn't actually able to print correctly and instead is just printing an ObjectID to the console. Might be useful to just use the arrayList and create a toString method for the broker objects to be printed to the console. Entirely up to you 👍

2022-04-02 21:55 UTC, Shmoogus commented on src/main/java/cryptoTrader/utils/BrokerManager.java
> +}
I kind of tossed that method in just to quickly see if it was working. I tried to take it out before I merged it

2022-04-02 21:56 UTC, csweet22 commented on src/main/java/cryptoTrader/utils/BrokerManager.java
> +}
All good then! I probably just had a commit behind yours

2022-04-02 23:36 UTC, Shmoogus commented on src/main/java/cryptoTrader/utils/BrokerManager.java
> +    private static BrokerManager manager = null;
good idea. I'll do that for the strategy factory as well

2022-04-02 23:36 UTC, Shmoogus commented on src/main/java/cryptoTrader/utils/BrokerManager.java
> +    }
done

2022-04-02 23:37 UTC, Shmoogus commented on src/main/java/cryptoTrader/utils/BrokerManager.java
> +        Strategy strategy = StrategyFactory.getInstance().getStrategy(strategyName);
oops

2022-04-03 00:48 UTC, csweet22 commented
LGTM!

2022-04-03 00:48 UTC, csweet22 approved these changes

2022-04-03 00:52 UTC, merged