TradeHistoryDatabase Implementation
csweet22/CS2212Group44 pull request #6
Opened 2022-04-02 20:51 UTC by Nchan8120

has the TradeHistoryDatabase class, TradeInterface class, and updates for trade, mainUI, dummyA strategy.

2022-04-02 21:26 UTC, csweet22 commented
What code do you need before we can implement the TradeHistory within the MainUI?

i.e. What do you need to get it displaying the history correctly?

2022-04-02 21:51 UTC, csweet22 requested changes

2022-04-02 21:51 UTC, csweet22 commented on src/main/java/cryptoTrader/gui/MainUI.java
> +		TradeHistoryDB tradeHistroyDB = TradeHistoryDB.getInstance();
Just a small spelling error in the variable name `tradeHistroyDB` should be `tradeHistoryDB`

2022-04-02 21:51 UTC, csweet22 commented on src/main/java/cryptoTrader/utils/DummyA.java
>          return null;
Just be careful about the return value here. Function signature says it returns a Trade object but the final line says it's returning null.

2022-04-02 21:51 UTC, csweet22 commented on src/main/java/cryptoTrader/utils/Trade.java
> +	String action;
These probably default to being private, but can we just include private in front of all the variables just for formatting reasons? These are all private right?

2022-04-02 21:51 UTC, csweet22 commented on src/main/java/cryptoTrader/utils/TradeHistoryDB.java
> +	}
Nitpicking (You can choose to ignore or change this): Can we format this just as `public TradeHistoryDB() {}` if it is going to be empty?

2022-04-02 23:35 UTC, Nchan8120 commented
> What code do you need before we can implement the TradeHistory within the MainUI?
> 
> i.e. What do you need to get it displaying the history correctly?

do you mean the table and histogram? if so that is Nick's part of the code. I'm focused on the process of making a trade

2022-04-03 15:34 UTC, csweet22 approved these changes

2022-04-03 15:35 UTC, merged